ISGWebSite/Areas/Yetki/Controllers/KullaniciController.cs
using Argem.DataServices;
using ArgemUtil;
using ISGWebSite.AppCode;
using ISGWebSite.Controllers;
using ISGWebSite.Models;
using ISGWebSite.Models.Yetki.Kullanici;
using System;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.Linq;
using System.Web.Mvc;
using VeriTabani;
using static ISGWebSite.Areas.Yetki.Models.GenelModel;

namespace ISGWebSite.Areas.Yetki.Controllers
{
    // https://www.youtube.com/watch?v=_r6laMn70FA paging
    // https://sroze.github.io/ngInfiniteScroll/demo_async.html

    public class KullaniciController : BaseController
    {
        public ActionResult YetkiVer()
        {
            return View();
        }

        public ActionResult KullaniciAra()
        {
            return View();
        }

        public JsonResult KullaniciAraSonuc(int SayfaKayitAdet, int AktifSayfaNo, int SiraTip, string SiraAlan, KullaniciModel oKullaniciModel)
        {
            // System.Threading.Thread.Sleep(2000);
            SonucModel<KullaniciAraModel> oSonucModel = new SonucModel<KullaniciAraModel>() { Durum = "H", Aciklama = "" };
            int ToplamKayitAdet = 0;

            ArgemSQL oSQL = new ArgemSQL();
            oSQL.CommandText =
                "select *, count(*) OVER() as \"Adet\" " +
                "from   public.\"KULLANICI\"";

            // string s = "ddsdf";
            // int i = Convert.ToInt32(s);

            if (!string.IsNullOrEmpty(oKullaniciModel.KullaniciAd))
                oSQL.Gecen("KullaniciAd", oKullaniciModel.KullaniciAd);
            else if (!string.IsNullOrEmpty(oKullaniciModel.Ad))
                oSQL.Gecen("Ad", oKullaniciModel.Ad);
            else if (!string.IsNullOrEmpty(oKullaniciModel.Soyad))
                oSQL.Gecen("Soyad", oKullaniciModel.Soyad);

            oSQL.Esit("KullaniciTipNo", oKullaniciModel.KullaniciTipNo, KolonTipi.Int, false);
            oSQL.Esit("AktifPasifTipNo", oKullaniciModel.AktifPasifTipNo, KolonTipi.Int, false);

            if (SiraAlan == "")
                oSQL.OrderByAsc("Ad,Soyad");
            else if (SiraTip == 1)
                oSQL.OrderByAsc(SiraAlan);
            else
                oSQL.OrderByDesc(SiraAlan);

            if (SayfaKayitAdet != 0 && AktifSayfaNo != 0)
                oSQL.KayitSayisiLimit(SayfaKayitAdet, AktifSayfaNo);

            using (DBUtil2 oData = new DBUtil2(DataBaseTipi.Yetki))
            {
                DataTable dt = new DataTable();
                oData.DataGetir(ref dt, oSQL);

                if (dt.Rows.Count > 0)
                {
                    ToplamKayitAdet = Convert.ToInt32(dt.Rows[0]["Adet"].ToString());

                    List<KullaniciAraModel> aryKullaniciAraModel = new List<KullaniciAraModel>();
                    foreach (DataRow dr in dt.Rows)
                    {
                        int KullaniciTipNo = Convert.ToInt32(dr["KullaniciTipNo"]);
                        int AktifPasifTipNo = Convert.ToInt32(dr["AktifPasifTipNo"]);
                        KullaniciAraModel oKullaniciAraModel = new KullaniciAraModel()
                        {
                            KullaniciKey = Convert.ToInt32(dr["KullaniciKey"]),
                            KullaniciAd = dr["KullaniciAd"].ToString(),
                            Ad = dr["Ad"].ToString(),
                            Soyad = dr["Soyad"].ToString(),
                            KullaniciTipNo = KullaniciTipNo,
                            KullaniciTipNoUzunAd = CacheHelper.LookUzunAdGetir(CacheHelper.DatabaseTipNo.Yetki, KullaniciTipNo),
                            AktifPasifTipNo = AktifPasifTipNo,
                            AktifPasifTipNoUzunAd = CacheHelper.LookUzunAdGetir(CacheHelper.DatabaseTipNo.Yetki, AktifPasifTipNo)
                        };
                        aryKullaniciAraModel.Add(oKullaniciAraModel);
                    }

                    oSonucModel.Durum = "";
                    oSonucModel.Data = aryKullaniciAraModel;
                }
                else
                    oSonucModel.Aciklama = "Aradığınız kritere uygun kullanıcı kaydı bulunamadı";

                oSonucModel.ToplamKayitAdet = ToplamKayitAdet;

                Stopwatch _stopwatch = (Stopwatch)TempData["ServerCalismaSure"];
                _stopwatch.Stop();
                oSonucModel.SCS = _stopwatch.ElapsedMilliseconds.ToString();

                return Json(oSonucModel, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult KullaniciGetir(string KullaniciKey)
        {
            // System.Threading.Thread.Sleep(2000);
            SonucModel<KullaniciModel> oSonucModel = new SonucModel<KullaniciModel>() { Durum = "H", Aciklama = "" };

            if (KullaniciKey == "" || KullaniciKey == "0")
            {
                List<KullaniciModel> aryKullaniciModel = new List<KullaniciModel>();
                // ilk kayıtta default verilerin dolu gelmesi için 
                KullaniciModel oKullaniciModel = new KullaniciModel()
                {
                    KullaniciKey = 0,
                    KullaniciTipNo = 1,
                    AktifPasifTipNo = 100
                };
                aryKullaniciModel.Add(oKullaniciModel);
                oSonucModel.Durum = "";
                oSonucModel.Data = aryKullaniciModel;
                return Json(oSonucModel, JsonRequestBehavior.AllowGet);
            }
            else
            {
                ArgemSQL oSQL = new ArgemSQL();
                oSQL.CommandText =
                    "SELECT * FROM public.\"KULLANICI\"";
                oSQL.Esit("KullaniciKey", KullaniciKey, KolonTipi.Int, true);

                using (DBUtil2 oData = new DBUtil2(DataBaseTipi.Yetki))
                {
                    DataTable dt = new DataTable();
                    oData.DataGetir(ref dt, oSQL);

                    if (dt.Rows.Count > 0)
                    {
                        List<KullaniciModel> aryKullaniciModel = new List<KullaniciModel>();
                        foreach (DataRow dr in dt.Rows)
                        {
                            int KullaniciTipNo = Convert.ToInt32(dr["KullaniciTipNo"]);
                            int AktifPasifTipNo = Convert.ToInt32(dr["AktifPasifTipNo"]);
                            KullaniciModel oKullaniciModel = new KullaniciModel()
                            {
                                KullaniciKey = Convert.ToInt32(dr["KullaniciKey"]),
                                KullaniciAd = dr["KullaniciAd"].ToString(),
                                Ad = dr["Ad"].ToString(),
                                Soyad = dr["Soyad"].ToString(),
                                KullaniciTipNo = KullaniciTipNo,
                                // KullaniciTipNoUzunAd = CacheHelper.LookUzunAdGetir(CacheHelper.DatabaseTipNo.Yetki, KullaniciTipNo),
                                AktifPasifTipNo = AktifPasifTipNo,
                                // AktifPasifTipNoUzunAd = CacheHelper.LookUzunAdGetir(CacheHelper.DatabaseTipNo.Yetki, AktifPasifTipNo)
                            };
                            aryKullaniciModel.Add(oKullaniciModel);
                        }

                        oSonucModel.Durum = "";
                        oSonucModel.Data = aryKullaniciModel;
                    }

                    return Json(oSonucModel, JsonRequestBehavior.AllowGet);
                }
            }
        }

        [HttpGet]
        public ActionResult KullaniciKayit(string Durum, string Key)
        {
            return PartialView();
        }

        [HttpPost]
        public JsonResult KullaniciKayit(KullaniciModel oKullaniciModel)
        {
            SonucModel<KullaniciModel> oSonucModel = new SonucModel<KullaniciModel>() { Durum = "H", Aciklama = "" };

            int KullaniciKey = oKullaniciModel.KullaniciKey;
            string KullaniciAd = oKullaniciModel.KullaniciAd;
            string Ad = oKullaniciModel.Ad;
            string Soyad = oKullaniciModel.Soyad;
            int KullaniciTipNo = oKullaniciModel.KullaniciTipNo;
            int AktifPasifTipNo = oKullaniciModel.AktifPasifTipNo;

            if (string.IsNullOrEmpty(KullaniciAd))
                oSonucModel.Aciklama = "Kullanıcı adı boş olamaz";
            else if (string.IsNullOrEmpty(Ad))
                oSonucModel.Aciklama = "Ad boş olamaz";
            else if (string.IsNullOrEmpty(Soyad))
                oSonucModel.Aciklama = "Soyad boş olamaz";
            else if (KullaniciTipNo == 0)
                oSonucModel.Aciklama = "Tip boş olamaz";
            else if (AktifPasifTipNo == 0)
                oSonucModel.Aciklama = "Durumu boş olamaz";
            else
            {
                if (KullaniciKey == 0)
                {
                    ArgemSQL oSQL = new ArgemSQL();
                    oSQL.CommandText =
                        "insert into public.\"KULLANICI\" " +
                        "       (\"KullaniciAd\", \"Ad\", \"Soyad\", \"KullaniciTipNo\", \"AktifPasifTipNo\", \"Parola\", \"UKullaniciKey\", \"UTar\") " +
                        "values ('" + KullaniciAd + "','" + Ad + "','" + Soyad + "', " + KullaniciTipNo + ", " + AktifPasifTipNo + ", '123', 1, current_timestamp) " +
                        "returning \"KullaniciKey\" ";
                    using (DBUtil2 oData = new DBUtil2(DataBaseTipi.Yetki))
                    {
                        string SonucKullaniciKey = Convert.ToString(oData.SorguCalistir(oSQL));
                        if (SonucKullaniciKey != "0")
                            oSonucModel.Durum = "";
                        else
                            oSonucModel.Aciklama = "Veri kaydedilemedi";
                    }
                }
                else
                {
                    ArgemSQL oSQL = new ArgemSQL();
                    oSQL.CommandText =
                        "update public.\"KULLANICI\" " +

ISGWebSite/Areas/Yetki/Controllers/YetkiGrupController.cs
using Argem.DataServices;
using ArgemUtil;
using ISGWebSite.AppCode;
using ISGWebSite.Areas.Yetki.Models.Kullanici;
using ISGWebSite.Controllers;
using ISGWebSite.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Web.Mvc;
using VeriTabani;

namespace ISGWebSite.Areas.Yetki.Controllers
{
    public class YetkiGrupController : BaseController
    {
        public ActionResult YetkiGrupAra()
        {
            return View();
        }

        public JsonResult YetkiGrupAraSonuc(YetkiGrupModel oYetkiGrupModel)
        {
            SonucModel<YetkiGrupModel> oSonucModel = new SonucModel<YetkiGrupModel>() { Durum = "H", Aciklama = "" };

            ArgemSQL oSQL = new ArgemSQL();
            oSQL.CommandText =
                "SELECT * FROM public.\"YETKI_GRUP\"";
            if (oYetkiGrupModel.YetkiGrupKey != 0)
                oSQL.Esit("YetkiGrupKey", oYetkiGrupModel.YetkiGrupKey, KolonTipi.Int, true);
            else if (!string.IsNullOrEmpty(oYetkiGrupModel.YetkiGrupAd))
                oSQL.Gecen("YetkiGrupAd", oYetkiGrupModel.YetkiGrupAd);
            oSQL.OrderByAsc("YetkiGrupAd");

            using (DBUtil2 oData = new DBUtil2(DataBaseTipi.Yetki))
            {
                DataTable dt = new DataTable();
                oData.DataGetir(ref dt, oSQL);

                if (dt.Rows.Count > 0)
                {
                    List<YetkiGrupModel> aryYetkiGrupModel = new List<YetkiGrupModel>();
                    foreach (DataRow dr in dt.Rows)
                    {
                        oYetkiGrupModel = new YetkiGrupModel()
                        {
                            YetkiGrupKey = Convert.ToInt32(dr["YetkiGrupKey"]),
                            YetkiGrupAd = dr["YetkiGrupAd"].ToString(),
                            S = 0
                        };
                        aryYetkiGrupModel.Add(oYetkiGrupModel);
                    }

                    oSonucModel.Durum = "";
                    oSonucModel.Data = aryYetkiGrupModel;
                }
                else
                    oSonucModel.Aciklama = "Aradığınız kritere uygun kayıt bulunamadı";

                return Json(oSonucModel, JsonRequestBehavior.AllowGet);
            }           
        }

        [HttpGet]
        public ActionResult YetkiGrupKayit(string Durum, string Key)
        {
            return PartialView();
        }

        [HttpPost]
        public JsonResult YetkiGrupKayit(YetkiGrupModel oYetkiGrupModel)
        {
            SonucModel<YetkiGrupModel> oSonucModel = new SonucModel<YetkiGrupModel>() { Durum = "H", Aciklama = "" };

            int YetkiGrupKey = oYetkiGrupModel.YetkiGrupKey;
            string YetkiGrupAd = oYetkiGrupModel.YetkiGrupAd;

            if (string.IsNullOrEmpty(YetkiGrupAd))
                oSonucModel.Aciklama = "Yetki grup adı boş olamaz";
            else
            {
                if (YetkiGrupKey == 0)
                {
                    ArgemSQL oSQL = new ArgemSQL();
                    oSQL.CommandText =
                        "insert into public.\"YETKI_GRUP\" " +
                        "       (\"YetkiGrupAd\", \"UKullaniciKey\", \"UTar\") " +
                        "values ('" + YetkiGrupAd + "'," + ArgemSession.OpKullaniciKey + ", current_timestamp) " +
                        "returning \"YetkiGrupKey\" ";

                    using (DBUtil2 oData = new DBUtil2(DataBaseTipi.Yetki))
                    {
                        string SonucYetkiGrupKey = Convert.ToString(oData.SorguCalistir(oSQL));
                        if (SonucYetkiGrupKey != "0")
                            oSonucModel.Durum = "";
                        else
                            oSonucModel.Aciklama = "Veri kaydedilemedi";
                    }
                }
                else
                {
                    ArgemSQL oSQL = new ArgemSQL();
                    oSQL.CommandText =
                        "update public.\"YETKI_GRUP\" " +
                        "set    \"YetkiGrupAd\" = '" + YetkiGrupAd + "', " +
                        "       \"UKullaniciKey\" = " + ArgemSession.OpKullaniciKey + ", " +
                        "       \"UTar\" = current_timestamp ";
                    oSQL.Esit("YetkiGrupKey", YetkiGrupKey, KolonTipi.Int, true);
                    using (DBUtil2 oData = new DBUtil2(DataBaseTipi.Yetki))
                    {
                        oData.SorguCalistir(oSQL);
                        oSonucModel.Durum = "";
                    }
                }
            }

            return Json(oSonucModel, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public PartialViewResult YetkiGrupOku(string Durum, string Key)
        {
            SonucModel<YetkiGrupModel> oSonucModel = new SonucModel<YetkiGrupModel>() { Durum = "H", Aciklama = "" };

            if (string.IsNullOrEmpty(Durum) && string.IsNullOrEmpty(Key))
            {
                oSonucModel.Aciklama = "Hatalı parametre";
                return PartialView(oSonucModel);
            }
            else
            {
                string sSQL = "SELECT * FROM public.\"YETKI_GRUP\"";
                sSQL += " where \"YetkiGrupKey\" = " + Key;
                DataSet ds = DBUtilPostger.VeriGetirDS(sSQL);
                if (ds.Tables[0].Rows.Count > 0)
                {
                    DataRow dr = ds.Tables[0].Rows[0];
                    YetkiGrupModel oYetkiGrupModel = new YetkiGrupModel()
                    {
                        YetkiGrupKey = Convert.ToInt32(dr["YetkiGrupKey"]),
                        YetkiGrupAd = dr["YetkiGrupAd"].ToString()
                    };

                    List<YetkiGrupModel> aryYetkiGrupModel = new List<YetkiGrupModel>();
                    aryYetkiGrupModel.Add(oYetkiGrupModel);

                    oSonucModel.Durum = Durum;
                    oSonucModel.Data = aryYetkiGrupModel;
                }
                else
                    oSonucModel.Aciklama = "Kayıt bulunamadı";
            }

            return PartialView(oSonucModel);
        }

        [HttpGet]
        public JsonResult YetkiGrupSil(string Key)
        {
            SonucModel<YetkiGrupModel> oSonucModel = new SonucModel<YetkiGrupModel>() { Durum = "H", Aciklama = "" };

            if (string.IsNullOrEmpty(Key))
                oSonucModel.Aciklama = "Silinecek kayda ulaşılamadı";
            else
            {
                string sSQL = "delete from public.\"YETKI_GRUP\"";
                sSQL += " where \"YetkiGrupKey\" = " + Key;
                string Sonuc = DBUtilPostger.SorguCalistir(sSQL);
                if (Sonuc == "0")
                    oSonucModel.Durum = "";
                else
                    oSonucModel.Aciklama = Sonuc;
            }

            return Json(oSonucModel, JsonRequestBehavior.AllowGet);
        }

    }
}

ISGWebSite/Areas/Yetki/Views/Login/AnaSayfa.cshtml
@{
    ViewBag.Title = "Ana Sayfa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
        
    <div class="col-sm-6">
        <div class="card">
            <h5 class="card-header Kusak">Favori İşlemler</h5>
            <div class="card-body">

                <ul class="list-group">
                    <li class="list-group-item py-2 KusakSagSol">
                        <span class="fa fa-star" style="padding-right:10px"></span>@Html.ActionLink("Kullanıcı İşlemleri", "KullaniciAra", "Kullanici", new { area = "Yetki" }, new { })
                    </li>
                    <li class="list-group-item py-2 KusakSagSol">
                        <span class="fa fa-star" style="padding-right:10px"></span>@Html.ActionLink("Yetki Grup İşlemleri", "YetkiGrupAra", "YetkiGrup", new { area = "Yetki" }, new { })
                    </li>
                    <li class="list-group-item py-2 KusakSagSol">
                        <span class="fa fa-star" style="padding-right:10px"></span>@Html.ActionLink("Kullanıcı Yetki İşlemleri", "YetkiVer", "Kullanici", new { area = "Yetki" }, new { })
                    </li>
                    <li class="list-group-item py-2 divider KusakSagSol"></li>
                    <li class="list-group-item py-2 KusakAlt"></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="col-sm-6">

        <div class="card">
            <h5 class="card-header Kusak">Sistem  Uyarıları</h5>
            <div class="card-body">


                <ul class="list-group">
                    <li class="list-group-item KusakSagSol">
                        <p>
                            <a data-toggle="collapse" href="#LMA1" role="button" aria-expanded="false" aria-controls="collapseExample">
                                <span class="fa fa-bell" style="padding-right:5px"></span>
                                Argem İSG modülü 01.01.2019 tarihi ile kullanıma açıldı
                            </a>
                        </p>
                        <div class="collapse" id="LMA1" style="padding-left:20px">
                            Argem İSG modülü 01.01.2019 tarihi ile kullanıma açıldı
                        </div>
                    </li>
                    <li class="list-group-item KusakSagSol">
                        <p>
                            <a data-toggle="collapse" href="#LMA2" role="button" aria-expanded="false" aria-controls="collapseExample">
                                <span class="fa fa-bell-o" style="padding-right:5px"></span>Teknik denetçi raporu için tıklayınız
                            </a>
                        </p>
                        <div class="collapse" id="LMA2" style="padding-left:20px">
                            Teknik denetçi raporu için tıklayınız
                        </div>
                    </li>
                    <li class="list-group-item KusakAlt">
                        <p>
                            <a data-toggle="collapse" href="#LMA3" role="button" aria-expanded="false" aria-controls="collapseExample">
                                <span class="fa fa-bell" style="padding-right:5px"></span>Eğitime başvuruları başladı. Sistem giriş yapıp eğitim başvurusunu onaylayınız.
                            </a>
                        </p>
                        <div class="collapse" id="LMA3" style="padding-left:20px">
                            Eğitime başvuruları başladı. Sistem giriş yapıp eğitim başvurusunu onaylayınız.
                        </div>
                    </li>
                </ul>

            </div>

        </div>

    </div>

</div>


@section Scripts {
    @Scripts.Render("~/JSNG/Yetki/AnaSayfa")
}

ISGWebSite/Areas/Yetki/Views/Login/HataKontrol.cshtml
@model System.Web.Mvc.HandleErrorInfo

@{
    ViewBag.Title = "HataKontrol";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-danger">Sistem Hatası</h1>
<h2 class="text-danger">Opps!!! Beklenmedik bir sistem hatası oluştu.</h2>
<h2 class="text-danger">Hata log sistemine kaydedildi. En kısa sürede çözüm üretilecektir.</h2>

@if (TempData["HataKey"] != null)
{
    <h2 class="text-danger">Hata kodu :@TempData["HataKey"].ToString()</h2>
}

@if (Model != null)
{
    <div>
        <h2>
            Hata Yeri :
        </h2>
        <h3>
            @Model.ControllerName
        </h3>
        <h2>
            Hata Mesajı :
        </h2>
        <h3>
            @Model.Exception.Message
        </h3>
        <h2>Data :</h2>
        <h3>
            @Model.Exception.Data
        </h3>
        <h2>Inner :</h2>
        <h3>
            @if (Model.Exception.InnerException != null)
            {
                @Model.Exception.InnerException.ToString()
            }

            @Model.Exception.InnerException.ToString()
        </h3>
        <h2>Source :</h2>
        <h3>
            @Model.Exception.Source
        </h3>
        <h2>Stack :</h2>
        <h3>
            @Model.Exception.StackTrace
        </h3>
        <h2>target :</h2>
        <h3>
            @Model.Exception.TargetSite
        </h3>
        <h2>tostr :</h2>
        <h3>
            @Model.Exception.ToString()
        </h3>
    </div>
}

ISGWebSite/Areas/Yetki/Views/Login/Login.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - İSG</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content" style="padding-top:100px">

        @{
            ViewBag.Title = "Giriş";
            ViewContext.ClientValidationEnabled = true;
        }

        <div class="row">
            <div class="col-md-12">
                <div style="padding-bottom:40px;text-align:center">
                    <img src="~/Resim/Ortak/KurumLogo.png" />
                </div>
            </div>
        </div>

        <div class="row" ng-app="ngaLogin" ng-controller="ngcLogin">
            <div class="col-md-6">

                <div class="card">
                    <h5 class="card-header Kusak">Sisteme Giriş</h5>
                    <div class="card-body">
                        <form name="frmLogin" ng-submit="SistemeGirisYap(frmLogin.$valid)" novalidate role="form">
                            <div class="row RowBosluk">
                                <div ng-show="HataVar" class="col-md-12 alert alert-danger ng-hide">
                                    {{HataAciklama}}
                                </div>
                            </div>
                            <div class="row RowBosluk">
                                <div class="col-md-4">
                                    <label for="KullaniciAd">Kullanıcı Adı :</label>
                                </div>
                                <div class="col-md-8">
                                    <input type="text" name="KullaniciAd" ng-model="KullaniciLoginModel.KullaniciAd"
                                           class="form-control" required autofocus />
                                </div>
                            </div>
                            <div class="row RowBosluk">
                                <div class="col-md-4">
                                    <label for="Parola">Parola :</label>
                                </div>
                                <div class="col-md-8">
                                    <input type="password" name="Parola" ng-model="KullaniciLoginModel.Parola" class="form-control"
                                           required autofocus />
                                </div>
                            </div>
                            <div class="row RowBosluk">
                                <div class="col-md-4">
                                </div>
                                <div class="col-md-8">
                                    <input type="checkbox" id="cbxKullaniciAdimiHatirla" ng-model="KullaniciLoginModel.KullaniciAdimiHatirla">
                                    <label for="cbxKullaniciAdimiHatirla">Kullanıcı adımı hatırla</label>
                                </div>
                            </div>
                            <div class="row RowBosluk">
                                <div class="col-md-4">
                                </div>
                                <div class="col-md-8">
                                    <button class="btn btn-primary" ng-disabled="GirisButonKapat">
                                        <span class="fa fa-sign-in"></span><span style="padding-left:15px"></span>Giriş
                                    </button>
                                    <button ng-click="SifremiUnuttum()" class="btn btn-light">
                                        <span class="fa fa-question-circle" style="padding-right:15px"></span>Şifremi Unuttum
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

            </div>

            <div class="col-md-6">

                <div class="card">
                    <h5 class="card-header Kusak">Duyurular</h5>
                    <div class="card-body">
                        <ul class="list-group">
                            <li class="list-group-item">
                                <p>
                                    <a data-toggle="collapse" href="#LMA1" role="button" aria-expanded="false" aria-controls="collapseExample">
                                        <span class="fa fa-bell" style="padding-right:5px"></span>
                                        Argem İSG modülü 01.01.2019 tarihi ile kullanıma açıldı
                                    </a>
                                </p>
                                <div class="collapse" id="LMA1" style="padding-left:20px">
                                    Argem İSG modülü 01.01.2019 tarihi ile kullanıma açıldı
                                </div>
                            </li>
                            <li class="list-group-item">
                                <p>
                                    <a data-toggle="collapse" href="#LMA2" role="button" aria-expanded="false" aria-controls="collapseExample">
                                        <span class="fa fa-bell-o" style="padding-right:5px"></span>Teknik denetçi raporu için tıklayınız
                                    </a>
                                </p>
                                <div class="collapse" id="LMA2" style="padding-left:20px">
                                    Teknik denetçi raporu için tıklayınız
                                </div>
                            </li>
                            <li class="list-group-item">
                                <p>
                                    <a data-toggle="collapse" href="#LMA3" role="button" aria-expanded="false" aria-controls="collapseExample">
                                        <span class="fa fa-bell" style="padding-right:5px"></span>Eğitime başvuruları başladı. Sistem giriş yapıp eğitim başvurusunu onaylayınız.
                                    </a>
                                </p>
                                <div class="collapse" id="LMA3" style="padding-left:20px">
                                    Eğitime başvuruları başladı. Sistem giriş yapıp eğitim başvurusunu onaylayınız.
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>

            </div>

        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/JSNG/Yetki/Login")

</body>
</html>